drop table member

CREATE TABLE member(
id VARCHAR2(50) PRIMARY KEY,
pw VARCHAR2(100) NOT NULL,
name VARCHAR2(30) NOT NULL,
gender VARCHAR2(10) NOT NULL,
email  VARCHAR2(100) NOT NULL,
address VARCHAR2(300) NOT NULL,
phone VARCHAR2(100) NOT NULL,
admin NUMBER NOT NULL,
money NUMBER NOT NULL,
point NUMBER NOT NULL,
regDate DATE DEFAULT SYSDATE,
updateDate DATE DEFAULT SYSDATE
)

SELECT * FROM MEMBER

ALTER TABLE member ADD phoneNumber NUMBER NOT NULL